In [1]:
import tensorflow as tf

tf.enable_eager_execution()
tf.executing_eagerly()

True

In [2]:
from test_in_training import get_data, composed, composed_new
lf, rf, hi = get_data()

# sess.run([lf, rf, hi])
lf.numpy(), rf.numpy(), hi.numpy()

(array([[0.5488135 , 0.71518934, 0.60276335],
        [0.5448832 , 0.4236548 , 0.6458941 ],
        [0.4375872 , 0.891773  , 0.96366274],
        [0.3834415 , 0.79172504, 0.5288949 ],
        [0.56804454, 0.92559665, 0.07103606],
        [0.0871293 , 0.0202184 , 0.83261985],
        [0.77815676, 0.87001216, 0.9786183 ],
        [0.7991586 , 0.46147937, 0.7805292 ],
        [0.11827443, 0.639921  , 0.14335328],
        [0.9446689 , 0.5218483 , 0.41466194]], dtype=float32),
 array([[0.2645556 , 0.7742337 , 0.45615032],
        [0.56843394, 0.0187898 , 0.6176355 ],
        [0.6120957 , 0.616934  , 0.94374806],
        [0.6818203 , 0.3595079 , 0.43703195],
        [0.6976312 , 0.06022547, 0.6667667 ],
        [0.67063785, 0.21038257, 0.12892629],
        [0.31542835, 0.36371076, 0.57019675],
        [0.43860152, 0.9883738 , 0.10204481],
        [0.20887676, 0.16130951, 0.6531083 ],
        [0.2532916 , 0.46631077, 0.2444256 ]], dtype=float32),
 array([7, 5, 5, 0, 1, 5, 9, 3, 0, 5], dtype=i

In [5]:
index = tf.multiply(tf.IndexedSlices(rf, hi, dense_shape=hi.shape), lf)
index = tf.square(tf.reduce_sum(index, axis=1))
# sess.run(index)
index

<tf.Tensor: id=24, shape=(10,), dtype=float32, numpy=
array([2.3055573 , 0.6994027 , 0.        , 1.0093604 , 0.        ,
       3.3152916 , 0.        , 0.8551689 , 0.        , 0.52448887],
      dtype=float32)>

In [ ]:
index2 = tf.square(tf.reduce_sum(tf.multiply(tf.gather(rf, hi), lf), axis=1))
sess.run(index2)

In [ ]:
sess.run(composed_new(lf, rf, hi))

In [ ]:
output = tf.placeholder('float', shape=[10, 3])
# dummy variable initialization
var_output = tf.Variable(initial_value=[[0]*3]*10, dtype=tf.float32)
print(var_output.shape)

tf.square(tf.reduce_sum(tf.multiply(
    tf.scatter_update(var_output,hi,rf), lf), axis=1))
sess.run(var_output)

In [32]:
v = tf.convert_to_tensor([88,99,100,200,300,400])
i = tf.convert_to_tensor([5,4,3,2,1,0])
r = tf.IndexedSlices(v,i, i.shape)
tf.multiply(r, tf.ones_like(r)).numpy()

array([400, 300, 200, 100,  99,  88], dtype=int32)